# Generated by Django 4.2.4 on 2024-01-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item'),
        ),
    ]
