# Generated by Django 5.1.4 on 2025-06-09 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0002_appartment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='image',
        ),
        migrations.AddField(
            model_name='appartment',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='appartments/covers/'),
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='appartments/gallery/')),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='appartments.appartment')),
            ],
        ),
    ]
